// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW2KhxT-R_O4SkI1b8VUTtFNuePQcjcdc',
    appId: '1:350162780158:web:3c837f2958d2e869c60aaf',
    messagingSenderId: '350162780158',
    projectId: 'flutterauth-be83e',
    authDomain: 'flutterauth-be83e.firebaseapp.com',
    storageBucket: 'flutterauth-be83e.appspot.com',
    measurementId: 'G-8XYMLX1TLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCureFfnu5Wyjx_nOZuY8TiUOqNGYH1xbA',
    appId: '1:350162780158:android:4fb5e985da2d7ffbc60aaf',
    messagingSenderId: '350162780158',
    projectId: 'flutterauth-be83e',
    storageBucket: 'flutterauth-be83e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDMhCbmBFcH5efnRWJgeT9WosYuBIVVzA',
    appId: '1:350162780158:ios:f76b63539bb1ab42c60aaf',
    messagingSenderId: '350162780158',
    projectId: 'flutterauth-be83e',
    storageBucket: 'flutterauth-be83e.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDMhCbmBFcH5efnRWJgeT9WosYuBIVVzA',
    appId: '1:350162780158:ios:51dec4af93ff0915c60aaf',
    messagingSenderId: '350162780158',
    projectId: 'flutterauth-be83e',
    storageBucket: 'flutterauth-be83e.appspot.com',
    iosBundleId: 'com.example.untitled1.RunnerTests',
  );
}
